// <auto-generated />
using System;
using LoyaltyCloud.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoyaltyCloud.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.BillingOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BankReference")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalCheckoutId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Months")
                        .HasColumnType("int");

                    b.Property<string>("PaymentKind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ReceiptUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("SubscriptionFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SubscriptionThroughUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BankReference")
                        .IsUnique()
                        .HasFilter("[BankReference] IS NOT NULL");

                    b.HasIndex("ExternalCheckoutId")
                        .IsUnique()
                        .HasFilter("[ExternalCheckoutId] IS NOT NULL");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("BillingOrders", null, t =>
                        {
                            t.HasCheckConstraint("CK_BillingOrders_Amounts", "[Subtotal]>=0 AND [Tax]>=0 AND [Total]>=0");

                            t.HasCheckConstraint("CK_BillingOrders_Months", "[Months] IN (1,3,6,12)");
                        });
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.BillingSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutomaticRenewalEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("BankName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("BankTransferEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("BankTransferInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeneficiaryName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("CardPaymentsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("CfdiEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Clabe")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("GracePeriodDays")
                        .HasColumnType("int");

                    b.Property<bool>("PricesIncludeTax")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireTransferReceipt")
                        .HasColumnType("bit");

                    b.Property<string>("SupportEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BillingSettings", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.CustomNotificationCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AudienceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DisplayUntilUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("IntendedRecipients")
                        .HasColumnType("int");

                    b.Property<string>("LongMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MinimumPoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("NotificationsCreated")
                        .HasColumnType("int");

                    b.Property<int>("NotificationsFailed")
                        .HasColumnType("int");

                    b.Property<int>("NotificationsSucceeded")
                        .HasColumnType("int");

                    b.Property<int?>("PointsExpiringDaysAhead")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ShortMessage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.HasIndex("TenantId", "ScheduledAtUtc");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("TenantId", "Status", "ScheduledAtUtc");

                    b.ToTable("CustomNotificationCampaigns", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("ReferredBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL AND [Email] <> ''");

                    b.HasIndex("TenantId", "IsActive");

                    b.HasIndex("TenantId", "NormalizedPhone")
                        .IsUnique()
                        .HasFilter("[NormalizedPhone] IS NOT NULL AND [NormalizedPhone] <> ''");

                    b.HasIndex("TenantId", "ReferredBy");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.DeviceRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DeviceLibraryIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PassTypeIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PushToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "DeviceLibraryIdentifier");

                    b.HasIndex("TenantId", "SerialNumber");

                    b.HasIndex("DeviceLibraryIdentifier", "PassTypeIdentifier", "SerialNumber")
                        .IsUnique();

                    b.ToTable("DeviceRegistrations", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.LoyaltyCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthenticationToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("int");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("LevelAchievedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("LifetimePoints")
                        .HasColumnType("int");

                    b.Property<int>("PointsEarnedThisYear")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "CustomerId")
                        .IsUnique();

                    b.ToTable("LoyaltyCards", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.LoyaltyNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("CustomNotificationCampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DisplayUntilUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LongMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("LoyaltyCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("ProcessingStartedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("ScheduledAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ShortMessage")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CorrelationId")
                        .IsUnique()
                        .HasFilter("[CorrelationId] IS NOT NULL");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.HasIndex("TenantId", "CustomNotificationCampaignId");

                    b.HasIndex("TenantId", "CustomerId");

                    b.HasIndex("TenantId", "LoyaltyCardId");

                    b.HasIndex("TenantId", "ScheduledAtUtc");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("TenantId", "Status", "ScheduledAtUtc");

                    b.ToTable("LoyaltyNotifications", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.MemberDigitalWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalClassId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ExternalObjectId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("LastSaveLinkCreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("LastSynchronizationError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("LastSynchronizedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("LoyaltyCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LoyaltyCardId");

                    b.HasIndex("Provider", "ExternalObjectId")
                        .IsUnique();

                    b.HasIndex("TenantId", "CustomerId", "Provider");

                    b.HasIndex("TenantId", "LoyaltyCardId", "Provider")
                        .IsUnique();

                    b.HasIndex("TenantId", "Provider", "Status");

                    b.ToTable("MemberDigitalWallets", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AttemptedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("DevicesFound")
                        .HasColumnType("int");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("LoyaltyNotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PushesAccepted")
                        .HasColumnType("int");

                    b.Property<int>("PushesAttempted")
                        .HasColumnType("int");

                    b.Property<int>("PushesFailed")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LoyaltyNotificationId");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("TenantId", "Channel", "Status");

                    b.ToTable("NotificationDeliveries", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BillingOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardBrand")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CardLast4")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("ExternalTransactionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FailureCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ReceiptUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BillingOrderId");

                    b.HasIndex("Provider", "ExternalTransactionId")
                        .IsUnique();

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("PaymentTransactions", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.PaymentWebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderEventId")
                        .IsUnique();

                    b.ToTable("PaymentWebhookEvents", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.PointCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LevelEligibility")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("MinimumPurchaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Multiplier")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EndsAtUtc");

                    b.HasIndex("TenantId", "IsActive");

                    b.HasIndex("TenantId", "StartsAtUtc");

                    b.HasIndex("TenantId", "IsActive", "StartsAtUtc", "EndsAtUtc");

                    b.ToTable("PointCampaigns", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.PointLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("LoyaltyCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OriginalAmount")
                        .HasColumnType("int");

                    b.Property<int>("RemainingAmount")
                        .HasColumnType("int");

                    b.Property<Guid>("SourcePointTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SourcePointTransactionId")
                        .IsUnique();

                    b.HasIndex("TenantId", "ExpiresAt", "RemainingAmount");

                    b.HasIndex("TenantId", "LoyaltyCardId", "ExpiresAt", "EarnedAt");

                    b.ToTable("PointLots", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.PointLotConsumption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid>("ConsumingPointTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("PointLotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RedemptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReversedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ConsumingPointTransactionId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.HasIndex("TenantId", "PointLotId");

                    b.HasIndex("TenantId", "RedemptionId")
                        .HasFilter("[RedemptionId] IS NOT NULL");

                    b.ToTable("PointLotConsumptions", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.PointTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AppliedMultiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("BasePoints")
                        .HasColumnType("int");

                    b.Property<string>("BonusType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("LoyaltyCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<decimal?>("PurchaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CampaignId")
                        .HasFilter("[CampaignId] IS NOT NULL");

                    b.HasIndex("TenantId", "LoyaltyCardId", "CreatedAt")
                        .IsDescending(false, false, true);

                    b.HasIndex("TenantId", "Type", "CreatedAt");

                    b.ToTable("PointTransactions", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.ProgramConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.ToTable("ProgramConfigs", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.Redemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ConfirmedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("LoyaltyCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MonetaryAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MonetaryCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("MonetaryPointsPerPesoUnit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PointsSpent")
                        .HasColumnType("int");

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("RewardCatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RewardCatalogItemId")
                        .HasFilter("[RewardCatalogItemId] IS NOT NULL");

                    b.HasIndex("TenantId", "LoyaltyCardId", "RedeemedAt");

                    b.HasIndex("TenantId", "Status", "RedeemedAt");

                    b.HasIndex("TenantId", "Type", "RedeemedAt");

                    b.ToTable("Redemptions", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.RewardCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMonthlyProduct")
                        .HasColumnType("bit");

                    b.Property<string>("MinLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PointsCost")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsActive");

                    b.HasIndex("TenantId", "IsMonthlyProduct");

                    b.HasIndex("TenantId", "MinLevel");

                    b.HasIndex("TenantId", "IsMonthlyProduct", "IsActive", "ValidFrom", "ValidTo");

                    b.ToTable("RewardCatalogItems", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthlyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("SixMonthPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StripeOneMonthPriceId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StripeSixMonthPriceId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StripeThreeMonthPriceId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StripeTwelveMonthPriceId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ThreeMonthPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TwelveMonthPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SubscriptionPlans", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.TenantAdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("TenantId", "NormalizedUsername")
                        .IsUnique();

                    b.ToTable("TenantAdminUsers", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.TenantBillingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoRenewEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("BillingContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("bit");

                    b.Property<string>("CardBrand")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CardLast4")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<decimal?>("RecurringAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RecurringCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("RecurringMonths")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StripeCurrentPeriodEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StripeSubscriptionStatus")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StripeCustomerId")
                        .IsUnique()
                        .HasFilter("[StripeCustomerId] IS NOT NULL");

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique()
                        .HasFilter("[StripeSubscriptionId] IS NOT NULL");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantBillingProfiles", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.TenantBranding", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InstagramUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LogoBlobName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SupportPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TermsUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("WalletBackgroundColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("WalletLogoBlobName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WhatsAppUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("TenantId");

                    b.ToTable("TenantBrandings", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.TenantLoyaltyLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Threshold")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("TenantId", "SortOrder")
                        .IsUnique();

                    b.HasIndex("TenantId", "Threshold")
                        .IsUnique();

                    b.HasIndex("TenantId", "IsActive", "SortOrder");

                    b.ToTable("TenantLoyaltyLevels", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.TenantSubscription", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CurrentPeriodEnd")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("CurrentPeriodStart")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("GracePeriodEndsAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("LastPaymentAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("PaidThroughUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TenantId");

                    b.HasIndex("Status");

                    b.ToTable("TenantSubscriptions", (string)null);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.BillingOrder", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.CustomNotificationCampaign", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.Customer", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.DeviceRegistration", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyaltyCloud.Domain.Entities.LoyaltyCard", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SerialNumber")
                        .HasPrincipalKey("TenantId", "SerialNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.LoyaltyCard", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyaltyCloud.Domain.Entities.Customer", null)
                        .WithOne()
                        .HasForeignKey("LoyaltyCloud.Domain.Entities.LoyaltyCard", "TenantId", "CustomerId")
                        .HasPrincipalKey("LoyaltyCloud.Domain.Entities.Customer", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.LoyaltyNotification", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyaltyCloud.Domain.Entities.CustomNotificationCampaign", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CustomNotificationCampaignId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LoyaltyCloud.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CustomerId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyaltyCloud.Domain.Entities.LoyaltyCard", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LoyaltyCardId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.MemberDigitalWallet", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyaltyCloud.Domain.Entities.LoyaltyCard", null)
                        .WithMany()
                        .HasForeignKey("LoyaltyCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.NotificationDelivery", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyaltyCloud.Domain.Entities.LoyaltyNotification", null)
                        .WithMany("Deliveries")
                        .HasForeignKey("TenantId", "LoyaltyNotificationId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.BillingOrder", null)
                        .WithMany()
                        .HasForeignKey("BillingOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.PointCampaign", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.PointLot", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyaltyCloud.Domain.Entities.LoyaltyCard", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LoyaltyCardId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyaltyCloud.Domain.Entities.PointTransaction", null)
                        .WithOne()
                        .HasForeignKey("LoyaltyCloud.Domain.Entities.PointLot", "TenantId", "SourcePointTransactionId")
                        .HasPrincipalKey("LoyaltyCloud.Domain.Entities.PointTransaction", "TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.PointLotConsumption", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyaltyCloud.Domain.Entities.PointTransaction", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ConsumingPointTransactionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyaltyCloud.Domain.Entities.PointLot", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PointLotId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyaltyCloud.Domain.Entities.Redemption", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RedemptionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.PointTransaction", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyaltyCloud.Domain.Entities.PointCampaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("TenantId", "CampaignId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LoyaltyCloud.Domain.Entities.LoyaltyCard", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LoyaltyCardId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.ProgramConfig", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.Redemption", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyaltyCloud.Domain.Entities.LoyaltyCard", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LoyaltyCardId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoyaltyCloud.Domain.Entities.RewardCatalogItem", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RewardCatalogItemId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.RewardCatalogItem", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.TenantAdminUser", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", "Tenant")
                        .WithMany("AdminUsers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.TenantBillingProfile", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", null)
                        .WithOne()
                        .HasForeignKey("LoyaltyCloud.Domain.Entities.TenantBillingProfile", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.TenantBranding", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", "Tenant")
                        .WithOne("Branding")
                        .HasForeignKey("LoyaltyCloud.Domain.Entities.TenantBranding", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.TenantLoyaltyLevel", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.TenantSubscription", b =>
                {
                    b.HasOne("LoyaltyCloud.Domain.Entities.Tenant", "Tenant")
                        .WithOne("Subscription")
                        .HasForeignKey("LoyaltyCloud.Domain.Entities.TenantSubscription", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.LoyaltyNotification", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("LoyaltyCloud.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("AdminUsers");

                    b.Navigation("Branding");

                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
