// <auto-generated />
using System;
using KBeauty.Loyalty.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KBeauty.Loyalty.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715012826_AddPointCampaignsAndTransactionAudit")]
    partial class AddPointCampaignsAndTransactionAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KBeauty.Loyalty.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("ReferredBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ReferredBy");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("KBeauty.Loyalty.Domain.Entities.DeviceRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DeviceLibraryIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PassTypeIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PushToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber");

                    b.HasIndex("DeviceLibraryIdentifier", "PassTypeIdentifier", "SerialNumber")
                        .IsUnique();

                    b.ToTable("DeviceRegistrations", (string)null);
                });

            modelBuilder.Entity("KBeauty.Loyalty.Domain.Entities.LoyaltyCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthenticationToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("int");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("LevelAchievedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("LifetimePoints")
                        .HasColumnType("int");

                    b.Property<int>("PointsEarnedThisYear")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("LoyaltyCards", (string)null);
                });

            modelBuilder.Entity("KBeauty.Loyalty.Domain.Entities.PointCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LevelEligibility")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("MinimumPurchaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Multiplier")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("EndsAtUtc");

                    b.HasIndex("IsActive");

                    b.HasIndex("StartsAtUtc");

                    b.HasIndex("IsActive", "StartsAtUtc", "EndsAtUtc");

                    b.ToTable("PointCampaigns", (string)null);
                });

            modelBuilder.Entity("KBeauty.Loyalty.Domain.Entities.PointLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("LoyaltyCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OriginalAmount")
                        .HasColumnType("int");

                    b.Property<int>("RemainingAmount")
                        .HasColumnType("int");

                    b.Property<Guid>("SourcePointTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SourcePointTransactionId")
                        .IsUnique();

                    b.HasIndex("ExpiresAt", "RemainingAmount");

                    b.HasIndex("LoyaltyCardId", "ExpiresAt", "EarnedAt");

                    b.ToTable("PointLots", (string)null);
                });

            modelBuilder.Entity("KBeauty.Loyalty.Domain.Entities.PointLotConsumption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid>("ConsumingPointTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("PointLotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RedemptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReversedAt")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumingPointTransactionId");

                    b.HasIndex("PointLotId");

                    b.HasIndex("RedemptionId");

                    b.ToTable("PointLotConsumptions", (string)null);
                });

            modelBuilder.Entity("KBeauty.Loyalty.Domain.Entities.PointTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AppliedMultiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("BasePoints")
                        .HasColumnType("int");

                    b.Property<string>("BonusType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("LoyaltyCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<decimal?>("PurchaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("LoyaltyCardId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("PointTransactions", (string)null);
                });

            modelBuilder.Entity("KBeauty.Loyalty.Domain.Entities.ProgramConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ProgramConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Description = "Pesos MXN por 1 punto (1 pt cada $10).",
                            Key = "points_per_peso_unit",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Value = "10"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Description = "Puntos al registrarse.",
                            Key = "welcome_bonus_points",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Value = "50"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            Description = "Puntos por referido confirmado.",
                            Key = "referral_bonus_points",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Value = "150"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            Description = "Multiplicador en mes de cumpleaños.",
                            Key = "birthday_multiplier",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Value = "2"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000f"),
                            Description = "Activa la expiracion automatica de puntos.",
                            Key = "points_expiration_enabled",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Value = "true"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000010"),
                            Description = "Meses de vigencia de cada lote de puntos.",
                            Key = "points_expire_after_months",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Value = "12"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000005"),
                            Description = "Umbral inicio nivel Mist.",
                            Key = "level_mist_min",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Value = "0"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000006"),
                            Description = "Umbral inicio nivel Glow.",
                            Key = "level_glow_min",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Value = "1000"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000007"),
                            Description = "Umbral inicio nivel Radiance.",
                            Key = "level_radiance_min",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Value = "3000"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000008"),
                            Description = "Puntos anuales para mantener Radiance.",
                            Key = "radiance_requalification_points",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Value = "500"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000009"),
                            Description = "Costo del mini producto.",
                            Key = "reward_mini_product_points",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Value = "300"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000a"),
                            Description = "Costo del $50 off en compra.",
                            Key = "reward_fifty_off_points",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Value = "500"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000b"),
                            Description = "Costo del análisis FocusSkin (Glow+).",
                            Key = "reward_focusskin_points",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Value = "400"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000c"),
                            Description = "Costo del producto del mes (Glow+).",
                            Key = "reward_monthly_product_points",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Value = "700"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000d"),
                            Description = "Costo del $100 off en cabina (Glow+).",
                            Key = "reward_hundred_off_cabina_points",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Value = "800"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-00000000000e"),
                            Description = "Costo del $300 off en facial (Radiance).",
                            Key = "reward_facial_off_points",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "system",
                            Value = "1200"
                        });
                });

            modelBuilder.Entity("KBeauty.Loyalty.Domain.Entities.Redemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ConfirmedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("LoyaltyCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PointsSpent")
                        .HasColumnType("int");

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("RewardCatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyCardId");

                    b.HasIndex("RewardCatalogItemId");

                    b.HasIndex("Status");

                    b.ToTable("Redemptions", (string)null);
                });

            modelBuilder.Entity("KBeauty.Loyalty.Domain.Entities.RewardCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMonthlyProduct")
                        .HasColumnType("bit");

                    b.Property<string>("MinLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PointsCost")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsMonthlyProduct");

                    b.ToTable("RewardCatalogItems", (string)null);
                });

            modelBuilder.Entity("KBeauty.Loyalty.Domain.Entities.LoyaltyCard", b =>
                {
                    b.HasOne("KBeauty.Loyalty.Domain.Entities.Customer", null)
                        .WithOne()
                        .HasForeignKey("KBeauty.Loyalty.Domain.Entities.LoyaltyCard", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KBeauty.Loyalty.Domain.Entities.PointLot", b =>
                {
                    b.HasOne("KBeauty.Loyalty.Domain.Entities.LoyaltyCard", null)
                        .WithMany()
                        .HasForeignKey("LoyaltyCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KBeauty.Loyalty.Domain.Entities.PointTransaction", null)
                        .WithOne()
                        .HasForeignKey("KBeauty.Loyalty.Domain.Entities.PointLot", "SourcePointTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KBeauty.Loyalty.Domain.Entities.PointLotConsumption", b =>
                {
                    b.HasOne("KBeauty.Loyalty.Domain.Entities.PointTransaction", null)
                        .WithMany()
                        .HasForeignKey("ConsumingPointTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KBeauty.Loyalty.Domain.Entities.PointLot", null)
                        .WithMany()
                        .HasForeignKey("PointLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KBeauty.Loyalty.Domain.Entities.Redemption", null)
                        .WithMany()
                        .HasForeignKey("RedemptionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("KBeauty.Loyalty.Domain.Entities.PointTransaction", b =>
                {
                    b.HasOne("KBeauty.Loyalty.Domain.Entities.PointCampaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KBeauty.Loyalty.Domain.Entities.LoyaltyCard", null)
                        .WithMany()
                        .HasForeignKey("LoyaltyCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("KBeauty.Loyalty.Domain.Entities.Redemption", b =>
                {
                    b.HasOne("KBeauty.Loyalty.Domain.Entities.LoyaltyCard", null)
                        .WithMany()
                        .HasForeignKey("LoyaltyCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KBeauty.Loyalty.Domain.Entities.RewardCatalogItem", null)
                        .WithMany()
                        .HasForeignKey("RewardCatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
