using LoyaltyCloud.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace LoyaltyCloud.Infrastructure.Persistence.Configurations;
internal sealed class GiftCardConfigurationMap : IEntityTypeConfiguration<GiftCardConfiguration> { public void Configure(EntityTypeBuilder<GiftCardConfiguration> b) { b.ToTable("GiftCardConfigurations"); b.HasKey(x=>x.Id); b.Property(x=>x.Currency).HasMaxLength(3); b.Property(x=>x.DisplayName).HasMaxLength(100); b.Property(x=>x.PrimaryColor).HasMaxLength(7); b.Property(x=>x.TextColor).HasMaxLength(7); b.Property(x=>x.LogoUrl).HasMaxLength(500); b.Property(x=>x.SecondaryText).HasMaxLength(200); b.Property(x=>x.Terms).HasMaxLength(2000); b.Property(x=>x.FooterMessage).HasMaxLength(300); b.Property(x=>x.ExpirationMode).HasConversion<string>().HasMaxLength(30); b.HasIndex(x=>x.TenantId).IsUnique(); b.HasOne<Tenant>().WithMany().HasForeignKey(x=>x.TenantId).OnDelete(DeleteBehavior.Cascade); } }
internal sealed class GiftCardDenominationMap : IEntityTypeConfiguration<GiftCardDenomination> { public void Configure(EntityTypeBuilder<GiftCardDenomination> b) { b.ToTable("GiftCardDenominations"); b.HasKey(x=>x.Id); b.Property(x=>x.Amount).HasPrecision(18,2); b.Property(x=>x.Currency).HasMaxLength(3); b.HasIndex(x=>new{x.TenantId,x.Amount,x.Currency}).IsUnique(); b.HasOne<Tenant>().WithMany().HasForeignKey(x=>x.TenantId).OnDelete(DeleteBehavior.Cascade); } }
internal sealed class GiftCardMap : IEntityTypeConfiguration<GiftCard> { public void Configure(EntityTypeBuilder<GiftCard> b) { b.ToTable("GiftCards"); b.HasKey(x=>x.Id); b.HasAlternateKey(x=>new{x.TenantId,x.Id}); b.Property(x=>x.PublicCode).HasMaxLength(32); b.Property(x=>x.ClaimTokenHash).HasMaxLength(64); b.Property(x=>x.InitialValue).HasPrecision(18,2); b.Property(x=>x.CurrentBalance).HasPrecision(18,2); b.Property(x=>x.Currency).HasMaxLength(3); b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(20); b.Property(x=>x.Source).HasConversion<string>().HasMaxLength(30); b.Property(x=>x.RecipientName).HasMaxLength(150); b.Property(x=>x.RecipientEmail).HasMaxLength(254); b.Property(x=>x.RecipientPhone).HasMaxLength(30); b.Property(x=>x.SenderName).HasMaxLength(150); b.Property(x=>x.PersonalMessage).HasMaxLength(500); b.Property(x=>x.RowVersion).IsRowVersion(); b.HasIndex(x=>x.PublicCode).IsUnique(); b.HasIndex(x=>x.ClaimTokenHash).IsUnique(); b.HasIndex(x=>new{x.TenantId,x.Status}); b.HasIndex(x=>new{x.TenantId,x.RecipientMemberId}); b.HasIndex(x=>new{x.TenantId,x.ExpiresAtUtc}); b.HasOne<Tenant>().WithMany().HasForeignKey(x=>x.TenantId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Customer>().WithMany().HasForeignKey(x=>x.RecipientMemberId).OnDelete(DeleteBehavior.SetNull); } }
internal sealed class GiftCardTransactionMap : IEntityTypeConfiguration<GiftCardTransaction> { public void Configure(EntityTypeBuilder<GiftCardTransaction> b) { b.ToTable("GiftCardTransactions"); b.HasKey(x=>x.Id); b.Property(x=>x.Type).HasConversion<string>().HasMaxLength(30); b.Property(x=>x.Amount).HasPrecision(18,2); b.Property(x=>x.BalanceBefore).HasPrecision(18,2); b.Property(x=>x.BalanceAfter).HasPrecision(18,2); b.Property(x=>x.Reference).HasMaxLength(200); b.Property(x=>x.Notes).HasMaxLength(1000); b.Property(x=>x.IdempotencyKey).HasMaxLength(100); b.HasIndex(x=>new{x.TenantId,x.GiftCardId,x.CreatedAtUtc}); b.HasIndex(x=>new{x.TenantId,x.IdempotencyKey}).IsUnique().HasFilter("[IdempotencyKey] IS NOT NULL"); b.HasOne<GiftCard>().WithMany().HasForeignKey(x=>x.GiftCardId).OnDelete(DeleteBehavior.Restrict); } }
internal sealed class GiftCardWalletMap : IEntityTypeConfiguration<GiftCardWallet> { public void Configure(EntityTypeBuilder<GiftCardWallet> b) { b.ToTable("GiftCardWallets"); b.HasKey(x=>x.Id); b.Property(x=>x.Provider).HasConversion<string>().HasMaxLength(20); b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(20); b.Property(x=>x.ExternalClassId).HasMaxLength(128); b.Property(x=>x.ExternalObjectId).HasMaxLength(128); b.Property(x=>x.AuthenticationToken).HasMaxLength(128); b.Property(x=>x.LastError).HasMaxLength(1000); b.HasIndex(x=>new{x.TenantId,x.GiftCardId,x.Provider}).IsUnique(); b.HasIndex(x=>new{x.Provider,x.ExternalObjectId}).IsUnique(); b.HasOne<GiftCard>().WithMany().HasForeignKey(x=>x.GiftCardId).OnDelete(DeleteBehavior.Cascade); } }
